IF OBJECT_ID('dbo.P_NOTA_FISCAL_ITEM_POR_CFOP') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.P_NOTA_FISCAL
    IF OBJECT_ID('dbo.P_NOTA_FISCAL_ITEM_POR_CFOP') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE dbo.P_NOTA_FISCAL_ITEM_POR_CFOP >>>'
    ELSE
        PRINT '<<< PROCEDURE dbo.P_NOTA_FISCAL_ITEM_POR_CFOP APAGADA >>>'
END
go
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 
CREATE PROCEDURE dbo.P_NOTA_FISCAL_ITEM_POR_CFOP
AS
BEGIN
	SELECT
		[CFOP] = [NFI].[Cfop]
	   ,[Valor Total da Base de ICMS] = SUM([NFI].[BaseIcms])
	   ,[Valor Total do ICMS] = SUM([NFI].[ValorIcms])
	   ,[Valor Total da Base de IPI] = SUM([NFI].[ValorIcms])
	   ,[Valor Total do IPI] = SUM([NFI].[BaseIcms]) --Atualmente é a mesma que o Icms
	FROM
		[dbo].[NotaFiscalItem] AS NFI WITH (NOLOCK)
	GROUP BY [Cfop]
END
GO
GRANT EXECUTE ON dbo.P_NOTA_FISCAL_ITEM_POR_CFOP TO [public]
go
IF OBJECT_ID('dbo.P_NOTA_FISCAL_ITEM_POR_CFOP') IS NOT NULL
    PRINT '<<< PROCEDURE dbo.P_NOTA_FISCAL_ITEM_POR_CFOP CRIADA >>>'
ELSE
    PRINT '<<< FALHA NA CRIACAO DA PROCEDURE dbo.P_NOTA_FISCAL_ITEM_POR_CFOP >>>'
go


